apiVersion: apps/v1
kind: Deployment
metadata:
  name: go_app
spec:
  selector:
    matchLabels:
      app: go_app
  template:
    metadata:
      labels:
        app: go_app
    spec:
      containers:
      - name: go_app
        image: celsinhobueno/go-hello-world:latest
        ports:
        - containerPort: 8080
